const express = require('express');
const router = express.Router();
const axios = require('axios');
const cheerio = require('cheerio');
const Sentiment = require('sentiment');
const fs = require('fs');
const path = require('path');
const ScannedNews = require('../models/News');

const sentiment = new Sentiment();

// =========================================================
// 🧠 INITIALIZATION: LOAD TRAINED DATA
// =========================================================
let threatDB = {};
try {
  // Load the JSON generated by Python
  const dbPath = path.join(__dirname, '../data/suspicious_keywords.json');
  const rawData = fs.readFileSync(dbPath, 'utf8');
  threatDB = JSON.parse(rawData);
  console.log(`✅ Multi-Factor Engine Loaded (Source: ${threatDB.meta.source})`);
} catch (err) {
  console.error("⚠️ Failed to load Threat DB (Using Fallback)", err.message);
  threatDB = { factors: { topic_triggers: { 'General': ['alien', 'conspiracy'] } } };
}

// Helper: Save to MongoDB
async function saveToDb(text, resultData) {
  try {
    const newRecord = new ScannedNews({
      articleText: text,
      verdict: resultData.verdict,
      confidence: resultData.confidence,
      reasons: resultData.reasons,
      apiUsed: resultData.apiUsed
    });
    await newRecord.save();
    console.log("💾 Result saved to DB.");
  } catch (err) { console.error("DB Save Error:", err.message); }
}

router.post('/check', async (req, res) => {
  try {
    let { text } = req.body;
    if (!text || text.length < 20) return res.status(400).json({ msg: 'Text too short.' });

    // 0. SCRAPER MODULE
    if (text.trim().startsWith('http')) {
      console.log("🔗 URL detected. Scraping...");
      try {
        const { data } = await axios.get(text, { headers: { 'User-Agent': 'Mozilla/5.0' } });
        const $ = cheerio.load(data);
        let scraped = "";
        $('p').each((i, el) => { scraped += $(el).text() + " "; });
        if (scraped.length > 50) text = scraped.trim();
      } catch (e) { console.log("⚠️ Scraper failed, using raw text."); }
    }

    console.log("⚙️ Running Multi-Factor Analysis...");
    let reasons = [];
    
    // =========================================================
    // 🔍 FACTOR 1: CONTENT (From ISOT Dataset)
    // =========================================================
    let contentScore = 0;
    const lowerText = text.toLowerCase();
    const topics = threatDB.factors.topic_triggers || {};
    
    Object.keys(topics).forEach(category => {
      const keywords = topics[category];
      const matches = keywords.filter(word => lowerText.includes(word));
      if (matches.length > 0) {
        contentScore += 30;
        reasons.push(`Found high-risk keywords`);
      }
    });

    // =========================================================
    // 🎨 FACTOR 2: TONE (Sentiment Analysis)
    // =========================================================
    let toneScore = 0;
    const sentimentResult = sentiment.analyze(text);
    if (sentimentResult.comparative < -0.3) {
      toneScore += 20;
      reasons.push("Tone is highly aggressive/negative.");
    }

    // =========================================================
    // 📐 FACTOR 3: STYLE (Formatting)
    // =========================================================
    let styleScore = 0;
    const puncCount = (text.match(/[!?]{2,}/g) || []).length;
    if (puncCount > 0) {
      styleScore += 15;
      reasons.push("Sensational punctuation detected.");
    }
    const upperCount = (text.match(/[A-Z]{3,}/g) || []).length;
    if (text.length > 50 && upperCount > 3) {
      styleScore += 15;
      reasons.push("Unprofessional use of CAPS.");
    }

    // =========================================================
    // 🧮 FINAL VERDICT
    // =========================================================
    const totalSuspicion = contentScore + toneScore + styleScore;
    let verdict = "Likely Real";
    let confidence = 75;

    if (totalSuspicion >= 50) {
      verdict = "Fake / Satire";
      confidence = Math.min(99, 60 + totalSuspicion);
    } else if (totalSuspicion >= 25) {
      verdict = "Unverified / Clickbait";
      confidence = 65;
    } else {
      reasons.push("Content aligns with standard news patterns.");
    }

    const result = {
      verdict, confidence, reasons,
      apiUsed: "MultiFactorEngine (ISOT-Trained)"
    };

    await saveToDb(text, result);
    res.json(result);

  } catch (err) {
    console.error("Error:", err.message);
    res.status(500).send('Server Error');
  }
});

module.exports = router;