import pandas as pd
import json
import re
from collections import Counter
from nltk.corpus import stopwords
import nltk

print("Initializing Natural Language Toolkit...")
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
stop_words.update(['said', 'would', 'could', 'one', 'like', 'time', 'people', 'via', 'video', 'image', 'news', 'media'])

print("Loading 'Fake.csv' (Training on first 3000 rows)...")
try:
    df = pd.read_csv('dataset/Fake.csv', nrows=3000)
    print(f"Loaded {len(df)} articles.")
except FileNotFoundError:
    print("Error: 'dataset/Fake.csv' not found.")
    exit()

print("Learning suspicious patterns...")
all_words = []

for text in df['text']:
    clean_text = re.sub(r'[^\w\s]', '', str(text).lower())
    words = clean_text.split()
    meaningful_words = [w for w in words if w not in stop_words and len(w) > 4]
    all_words.extend(meaningful_words)

word_counts = Counter(all_words)
top_triggers = [word for word, count in word_counts.most_common(50)]

print(f"Discovered Top Triggers: {top_triggers[:10]}...")

output_data = {
    "meta": {
        "source": "Fake News Dataset",
        "description": "Generated by Python NLP Analysis"
    },
    "factors": {
        "topic_triggers": {
            "High_Frequency_Fakes": top_triggers,
            "Supernatural": ["zombie", "undead", "vampire", "ghost", "demon", "spirit"],
            "SciFi_Fringe": ["alien", "ufo", "extraterrestrial", "teleport", "clone", "mind control"],
            "Conspiracy": ["illuminati", "deep state", "chemtrail", "false flag", "hoax", "cover-up"]
        },
        "style_triggers": {
            "Clickbait": ["shocking", "exposed", "secret", "viral", "banned", "won't tell you"],
            "Urgency": ["act now", "limited time", "delete this", "before it's too late"]
        }
    }
}

with open('data/suspicious_keywords.json', 'w') as f:
    json.dump(output_data, f, indent=2)

print("Success. sus kw saved to 'data/suspicious_keywords.json'.")