import pandas as pd
import json
import re
from collections import Counter
from nltk.corpus import stopwords
import nltk

# 1. SETUP & DOWNLOADS
print("⏳ Initializing Natural Language Toolkit...")
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
# Add common non-suspicious words to ignore
stop_words.update(['said', 'would', 'could', 'one', 'like', 'time', 'people', 'via', 'video', 'image', 'news', 'media'])

# 2. LOAD DATASET
print("📂 Loading 'Fake.csv' (Training on first 3000 rows)...")
try:
    # Reading a subset for speed. Remove 'nrows' for full training.
    df = pd.read_csv('dataset/Fake.csv', nrows=3000)
    print(f"✅ Loaded {len(df)} articles.")
except FileNotFoundError:
    print("❌ Error: 'dataset/Fake.csv' not found.")
    exit()

# 3. EXTRACT FEATURES
print("🧠 Learning suspicious patterns...")
all_words = []

for text in df['text']:
    # Clean text: remove punctuation, lowercase
    clean_text = re.sub(r'[^\w\s]', '', str(text).lower())
    words = clean_text.split()
    # Keep only meaningful words (len > 4)
    meaningful_words = [w for w in words if w not in stop_words and len(w) > 4]
    all_words.extend(meaningful_words)

# 4. IDENTIFY TOP TRIGGERS
word_counts = Counter(all_words)
# Get top 50 most frequent words in fake news
top_triggers = [word for word, count in word_counts.most_common(50)]

print(f"🔍 Discovered Top Triggers: {top_triggers[:10]}...")

# 5. GENERATE THREAT DB
output_data = {
    "meta": {
        "source": "ISOT Fake News Dataset",
        "version": "2.0-AutoTrained",
        "description": "Generated by Python NLP Analysis"
    },
    "factors": {
        "topic_triggers": {
            # The script auto-generates this list from real data
            "High_Frequency_Fakes": top_triggers,
            # We keep these manual categories for specific logic
            "Supernatural": ["zombie", "undead", "vampire", "ghost", "demon", "spirit"],
            "SciFi_Fringe": ["alien", "ufo", "extraterrestrial", "teleport", "clone", "mind control"],
            "Conspiracy": ["illuminati", "deep state", "chemtrail", "false flag", "hoax", "cover-up"]
        },
        "style_triggers": {
            "Clickbait": ["shocking", "exposed", "secret", "viral", "banned", "won't tell you"],
            "Urgency": ["act now", "limited time", "delete this", "before it's too late"]
        }
    }
}

# 6. SAVE TO JSON
with open('data/suspicious_keywords.json', 'w') as f:
    json.dump(output_data, f, indent=2)

print("💾 Success! Knowledge Base saved to 'data/suspicious_keywords.json'.")